### PR TITLE
Support Django 3.2 and drop Django 1.11, 2.0, and 2.1.

### PR DESCRIPTION
**Pull request by adamchainz**
* Add to tox and travis grids.
* Add new setting.

### CODE REVIEW

**Comment by adamchainz** [comment]
Looks like the coveralls setup is broken:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/coveralls/api.py", line 260, in wear
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by Gagaro** [comment]
Thanks :+1: .

I'll fix the actions after the merge. I have to see if spatialite still works here because it doesn't work with the exact same configuration in django-geojson.

**Comment by adamchainz** [comment]
Would it be possible to have a release, for both my Django 3.1 and 3.2 PR's?

**Comment by Gagaro** [comment]
Sure, released in 0.28.0. I'll also release django-geojson right now.

**Pull request merged**
