### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@Gagaro, I'm fine with also dropping Django 1.11 and/or 2.0, 2.1, but I thought this commit was already big enough. And maybe dropping DJango 1.11 would not be such a gain after all.

**Comment by Gagaro** [comment]
If we drop Python 2 we should also drop support for 1.11, as 1.11 is supposed to work with Python 2.

I'll merge this PR as it is and will probably remove mention from 1.11 in the README / travis. Thanks again.

**Comment by claudep** [comment]
I would not be shocked to see a package advertising support for Django 1.11 with Python 3 only, but your choice!

**Comment by Gagaro** [comment]
The thing is a lot of people stuck with Python 2 are also stuck with Django 1.11. Upgrading from 1.11 to 2.x is way easier when you are already on Python 3 but impossible with Python 2.

So removing support for Python 2 is as good as removing it for Django 1.11 for a lot of projects. That's why I don't like having one without the other.

**Comment by claudep** [comment]
I understand your POV. However, one could also argue that when you have to migrate to Python 3 (assuming your are on Django 1.11), it's easier to change from Python 2 to Python 3 without changing the Django version, then migrating to Django 2.x in a second step, to not mix upgrade concerns.

**Comment by Gagaro** [comment]
We're not concerned with that case here though as the current version is compatible with both Python 2 and 3. You can already upgrade from Python 2 to 3 without upgrading Django.

I prefer dropping the whole thing rather than maintaining half a version. But obviously, both solutions have pros and cons.

**Comment by claudep** [comment]
Sure, go ahead!

**Pull request merged**
