### PR TITLE
Update travis matrix

### PR DESCRIPTION
**Pull request by askpatrickw**
I'm not setup to run Travis locally so I'm relying on the CI to verify this.

As in the commit message:  Update the versions for travis

    * Removed no longer supported version of Django (1.6, 1.7, 1.9, 1.10) 1.11 is LTS
    * Added Django 2.0.7 explicitly
    * Removed Python 3.5, kept 3.6 
    * To support those changes, updated the matrix.exclude section to match.
    * Kept allow_failures for Django Dev

### CODE REVIEW

**Comment by W7PEA** [comment]
OK, this looks ready to merge.
I don't understand why Django Dev fails. but hey, its Django Dev. Seem unrelated to my changes, but if others have more guidance, let me know.
I filed another issue to track adding Py3.7 to the matrix #230

**Comment by Gagaro** [comment]
Hi, thanks for the PR. A few remarks:

* `Removed no longer supported version of Django (1.6, 1.7, 1.9, 1.10) 1.11 is LTS`
    * Please let them. Some people still relied on them. We will think about dropping them if they break with newer version of django,leaflet or if a new feature/optimization doesn't work with them. As long as  they work correctly with the current version, there is no reason to remove them from travis.
* `Added Django 2.0.7 explicitly`
    * 👍 
* `Removed Python 3.5, kept 3.6 `
    * Django 1.11 and 2.0 both support Python 3.5. We must let it. And we should actually add 3.4 as they also both support it.
* `To support those changes, updated the matrix.exclude section to match.`
* `Kept allow_failures for Django Dev`
    * This is used to see if there are new dev required with the next Django version automatically before its release. Failures are indeed expected.

**Comment by W7PEA** [comment]
I added back 3.4 & 3.5.

While I understand your point on the older Django releases (I get it, people don't upgrade.). I think you should reconsider if actively enabling people to stay on old versions which are very likely to have security issues is a sound practice. 1.10 was End Of Life 8 Months ago and hasn't had a release in 11 months.

image

So if you want to add that back, you won't hurt my feelings, but I would counsel against it.

In the future, I'll open an Issue and get your input before I PR. I really wanted to get 2.0 added though, it had been sitting out there way too long.

**Comment by Gagaro** [comment]
I agree with you but some people are just stuck on older versions. Removing them from travis won't help them. They'll either try the latest version and hope it works or use the latest tested one.

At least with Travis we can document which versions still works.

**Comment by W7PEA** [comment]
@Gagaro As you have requested and rolled forward and added even more new versions.

**Comment by Gagaro** [comment]
Thanks for the update, we're almost there 👍 . There are still two small things:

* Travis can't parse the `.travis.yml` file. I think it is because of the indentation of 

```
  - python: 2.7
      env: DJANGO_VERSION=dev DATABASE=sqlite	      env: DJANGO_VERSION=dev DATABASE=sqlite
```

* You didn't add the 3.7 to the exclude matrix. Only the 2.0 to 2.2 (dev) should be tested with it.

I think it should be all good after that.

**Comment by W7PEA** [comment]
Thanks for being patient with me on this... ;-)  Things are looking better.

Couple of items
1. Without the fix from Travis for issue #230 (they don't support 3.7 yet) we can either hold this PR till then, or move 3.7 to allowed failures.
2. I'm looking into why all the Django-dev run version failed to make sure that's not a real issue.

**Comment by W7PEA** [comment]
In looking at the Django-dev version failures... I don't see why we'd have path issues but the internet says `AttributeError: /usr/lib/libgdal.so.1: undefined symbol: GDALGetMetadataDomainList` is usually problem with your `GDAL_LIBRARY_PATH`. But for it to only fail with dev where 3.5|2.1|postgres passes points to something else. 

No related issues in Django Bug Tracker.

Let me know how you'd like to proceed given those failures and then I'll do a final submit.

**Comment by W7PEA** [comment]
@Gagaro  when you have some time, there are questions above for you to consider. tx!

**Comment by Gagaro** [comment]
We can probably wait for travis to add it. Ping me when it's ok.

For the dev version, we are far from the next release, we can ignore it for now.

**Comment by claudep** [comment]
I guess this PR is now mostly outdated.

**Comment by Gagaro** [comment]
Yes it is, thanks for the cleanup.

**Pull request closed without merging**
