### PR TITLE
Add support for Django 4.2

### PR DESCRIPTION
**Pull request by ducdetronquito**
Hi !

Django 4.2 has been released early this april and it would be great to see if django-leaflet supports it :)

I didn't contributed before so my appologies if I forgot something in this PR: don't hesitate to point out if anything needs to be fixed.

### CODE REVIEW

**Comment by Gagaro** [comment]
Hi, thanks for the PR :+1: .

It looks like there are a few deprecation warnings we should get rid of first.

**Comment by claudep** [comment]
PR #363 might be a first step getting rid of the deprecation warnings.

**Comment by Gagaro** [comment]
Merged manually, thanks to both of you :confetti_ball: .

**Comment by Gagaro** [comment]
Also just released in 0.29.0

**Comment by claudep** [comment]
Thanks :rocket:

**Pull request closed without merging**
