### PR TITLE
Drop support for Django < 1.11

### PR DESCRIPTION
**Pull request by claudep**
This PR is based on #282, I can rebase once #282 is pushed.

### CODE REVIEW

**Comment by claudep** [comment]
Rebased.

**Comment by claudep** [comment]
Sorry, just realized I forgot to update the Travis file, will do ASAP.

**Comment by Gagaro** [comment]
Thanks for the cleanup :+1: .

**Comment by claudep** [comment]
Just to know, are you ready to drop support for Python 2 now, or would you prefer keeping it for some time longer?

**Comment by Gagaro** [comment]
I'm ok with dropping python 2 if we drop Django 1.11 as well. We can also drop Django 2.0 and 2.1 if that helps but from experience supporting from 2.0 through 2.2 is pretty similar.

**Pull request merged**
