### PR TITLE
Remove debug print added in #371

### PR DESCRIPTION
**Pull request by jieter**
Remove debug print added in #371.

### CODE REVIEW

**Comment by Gagaro** [comment]
Thanks for the PR :+1:

**Comment by jieter** [comment]
Thanks for merging!

It would be nice to get this in a release, it will greatly reduce the noise in our test output.

**Comment by Gagaro** [comment]
Sure thing, released in 0.30.1.

**Comment by jieter** [comment]
> Sure thing, released in 0.30.1.


Thanks!

**Pull request merged**
