### PR TITLE
Upgrade Leaflet to 1.1.0

### PR DESCRIPTION
**Pull request by xusy2k**
It contains fix for #188

I've sent a [PR 5655](https://github.com/Leaflet/Leaflet/pull/5655)  and I checked my map is still working with django-leaflet-0.22.0 and Leaflet 1.1.0 embedded but I have not checked in depth

### CODE REVIEW

**Comment by xusy2k** [comment]
I've been too much optimist. With Mushroom spots sample I found [this bug](https://github.com/Leaflet/Leaflet.draw/issues/739) 

Enough for discard this pull request and delete my branch for avoid problems.

**Comment by Gagaro** [comment]
Thanks anyway, we should wait for a fix in leaflet.draw and try again after.

**Comment by janfabry** [comment]
[Leaflet 1.2.0 has been released](http://leafletjs.com/2017/08/08/leaflet-1.2.0.html), and has a workaround to re-enable this (many plugins were broken). [Leaflet.draw works now](https://github.com/Leaflet/Leaflet.draw/issues/739#issuecomment-321656482), so maybe we could try the upgrade again?

**Comment by Gagaro** [comment]
You're welcome to do a PR :smile: .

**Pull request closed without merging**
