### PR TITLE
Fix problem with wrong url for marker-icon when using hashed static

### PR DESCRIPTION
**Pull request by bonega**
When using cache-busting `marker-icon.png` is collected as `marker-icon.2273e3d8ad92.png` (example).
Leaflet is failing to handle this case correctly and will output an url like `marker-icon.2273e3d8ad92)%22.png`.
Obviously we can't lookup that result.

Small fix applied in regexp replace for the url.
issue originally reported in #188 and fixed in #197 
Unfortunately another update of Leaflet removed the fix.
New fix compiled from Leaflet `1.3.1` 
See commit in leaflet repo: https://github.com/bonega/Leaflet/commit/294b9dd28f5012249649a2ab031fa0f6d082932b

### CODE REVIEW

**Comment by Gagaro** [comment]
DId you try upgrading leaflet first? This is the 1.3.1 and the 1.6.0 has been released last month.

Your change would be lost when we upgrade it.

**Comment by bonega** [comment]
I used 1.3.1 because it is the same version as in django-leaflet master.
In order do keep the changes minimal.
From what I know the same problem is in 1.6.0

**Comment by Gagaro** [comment]
Looks like something which should be addressed in Leaflet, did you do a PR there?

**Comment by bonega** [comment]
https://github.com/Leaflet/Leaflet/issues/6585
I think they don't want to fix it in leaflet master.
Though there is this one: https://github.com/ghybs/leaflet-defaulticon-compatibility
Perhaps enables some sort of compatibility.
Will try to look at it.

**Comment by dbinetti** [comment]
Just checking to see if this is going to be merged...

**Comment by Gagaro** [comment]
This is an issue with leaflet, not with django-leaflet.

**Pull request closed without merging**
