### PR TITLE
Fix for non-default STATICFILES_STORAGE (supersedes #149)

### PR DESCRIPTION
**Pull request by KostyaEsmukov**
An implementation of a fix for #149.

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
Hi @leplatrem ,

I have just tested it with the included mushrooms example app and I confirm that the problem has gone. I.e. `collectstatic` with `ManifestStaticFilesStorage` and disabled `DEBUG` works flawlessly, generated static links contain hashes - everything is fine.

I hope the code is not too magical - I tried to make it clear, but feel free to raise your concerns.

Waiting for a code review now.

The #149 should be closed when this PR is merged.

**Comment by leplatrem** [comment]
@gutard hi! I would in favor of merging this, but don't want to do without your consent since it introduces a good amount of code. What do you think?

**Comment by adriantre** [comment]
Oh, when can I get this update? :)

**Comment by leplatrem** [comment]
It seems that I'm the only one to receive Github notifications. 

I'll merge, because YOLO :)

**Pull request merged**
