### PR TITLE
Add request to formfield_for_dbfield signature; fix #260

### LINKED ISSUE #260: Add request to formfield_to_dbfield
In v1.10, Django updated the signature of `formfield_to_dbfield` (https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/admin.py#L29) to contain `request`, but django-leaflet still does not pass request on.

As libraries such as https://github.com/deschler/django-modeltranslation/ have recently noticed this and fixed the signature accordingly (https://github.com/deschler/django-modeltranslation/issues/510), django-leaflet can no longer be used in combination with those, until the corresponding fix is implemented here.

### PR DESCRIPTION
**Pull request by Rikuoja**

### CODE REVIEW

**Comment by Gagaro** [comment]
Hi, thanks for the PR.

For backward compatibility, the signature should probably be `(self, db_field, request=None, **kwargs)`.

I'm not sure why but travis was disabled for this repository. Could you add a line in the `CHANGES` file and commit/push again so it triggers it.

Thanks :+1:

**Comment by Gagaro** [comment]
The CI seems to be broken right now: https://travis-ci.org/makinacorpus/django-leaflet/builds/597613725

**Comment by Rikuoja** [comment]
> Hi, thanks for the PR.
> 
> For backward compatibility, the signature should probably be `(self, db_field, request=None, **kwargs)`.
> 
> I'm not sure why but travis was disabled for this repository. Could you add a line in the `CHANGES` file and commit/push again so it triggers it.

Fixed the signature.

Travis seems to have changed some postgres and postgis package names lately, so we've had to update them to new versions to fix the CI: https://github.com/City-of-Helsinki/linkedevents/commit/a71c546eb02df1a11653bf4c005d0981eb29cc13#diff-354f30a63fb0907d4ad57269548329e3

**Comment by Rikuoja** [comment]
Rebase done! 👍

**Comment by Gagaro** [comment]
Thanks :+1:

**Pull request merged**
