### PR TITLE
Remove unsafe-inline

### PR DESCRIPTION
**Pull request by rodolvbg-divineslns**
#334

### CODE REVIEW

**Comment by claudep** [comment]
Just for history, the line was introduced in 35b3b72bb1f1, but at first sight I cannot see a reason it could not be moved to the css file. :+1:

**Comment by Gagaro** [comment]
It can't be moved in this css file because it is the CSS file directly from leaflet, so it will be lost next time we upgrade it.

We should create a new CSS file to include, such as `leaflet/leaflet.extras.css` to stay consistent with the JS one.

**Comment by claudep** [comment]
Ah, of course, how I missed that :-) An extra css is indeed the proper solution.

**Comment by Gagaro** [comment]
Thanks for the update :+1: , LGTM, you can remove the draft status if you are done with it.

**Comment by Gagaro** [comment]
See #371

**Pull request closed without merging**
