### PR TITLE
Update to Leaflet 1.0.1

### PR DESCRIPTION
**Pull request by sikmir**
Issue #166.

### CODE REVIEW

**Comment by leplatrem** [comment]
Leaflet draw might have to be updated as well no? (0.4 for 1.0 comptability)

**Comment by sikmir** [comment]
[Proj4Leaflet](https://github.com/kartena/Proj4Leaflet) is not 1.0 compatible yet:

> For compatibility with Leaflet 1.0-beta1 use the leaflet-proj-refactor branch.

**Comment by hairychris** [comment]
https://github.com/kartena/Proj4Leaflet/pull/126

Probably worth waiting for things to be resolved over there before creating a new release here.

**Comment by sikmir** [comment]
Proj4Leaflet 1.0.0 is out.

**Comment by leplatrem** [comment]
Can someone please try out and approve the changes of this branch?

**Comment by leplatrem** [comment]
You know what. I'll merge, 'cause *I'm feeling lucky* :)

**Comment by sikmir** [comment]
I have not tested it carefully yet, so it'd be worth if someone would try it out.

**Comment by leplatrem** [comment]
I released version 0.20 with the upgrade. Issues will be opened if there are bugs... «Release early» they say :)

**Comment by thrownblown** [comment]
i'm getting a bunch of bugs with leafletforms.js and leaflet.draw.js regarding mulitpolygons that i didn;t have with version 0.7 (eg these templates used to work.....):

original error regarding multipolygon:

image

i hacked that with `L.multiPolygon = L.polygon` which led me to this issue with leaflet.draw.js and some featureGroup inheritance bananas:

image

**Comment by leplatrem** [comment]
I'm not surprised that bugs were introduced. Don't hesitate to open a pull-request with some fixes, we'll release.

*We're looking for maintainers! ...currently overlooking patches, merging and releasing is the only thing I can do, at a very low frequency*

**Comment by thrownblown** [comment]
it has something to do with the widget (obviously). there seems to be some incompatibility with the L.GeometryField class and leaflet 1.0. is this a dependency that needs to be updated too?

I've dug back to here:

https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templates/leaflet/widget.html#L20

that's the line in the widget template, and here's how its rendering:

```
<script type="text/javascript">
    var geodjango_id_zone_polygon = {};
    geodjango_id_zone_polygon.fieldid = 'id_zone_polygon';
    geodjango_id_zone_polygon.modifiable = true;
    geodjango_id_zone_polygon.geom_type = 'MultiPolygon';
    geodjango_id_zone_polygon.srid = 4326;
    
    function id_zone_polygon_map_callback(map, options) {
        geodjango_id_zone_polygon.store_class = L.FieldStore;
        (new L.GeometryField(geodjango_id_zone_polygon)).addTo(map);
        
    };
</script>
```
I haven't dug through too much of the nuts and bolts of django-leaflet since it always worked so well! when I get it fixed i'll make pr

**Pull request merged**
