### PR TITLE
Upgrade Leaflet Draw to 0.3.0-dev

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by leplatrem** [comment]
Any argument in favor of merging a «dev» version?

**Comment by fanquake** [comment]
Aren't we already using a dev version, i.e [0.2.4-dev](https://github.com/makinacorpus/django-leaflet/pull/153/files#diff-cd0c53684d68ec5cdb084e084904f752L13) ? 0.3.0 is just the [newest release](https://github.com/Leaflet/Leaflet.draw/releases).

**Comment by leplatrem** [comment]
Great that 0.3 was released! Does this PR embed the tagged version?

**Comment by fanquake** [comment]
As far as I can remember, yes it does contain the tagged version.

**Comment by leplatrem** [comment]
capture d ecran de 2016-06-30 15-02-55

**Comment by seav** [comment]
Hi! May I know if this PR will be merged soon or if there's a timetable for this?

**Comment by leplatrem** [comment]
I was a bit reluctant to embed a dev version to be honest, that's why I didn't merge it immediately. I'd prefer to let @gutard decide...

**Comment by raratiru** [comment]
This seems to be a key decision since a few weeks ago, for a reason I cannot understand, the touch events ceased responding even in the widget that caters for entering a single Point.

Probably it was an unexpected surprise that it worked during the last six months I use it and I did not know about it... 

I am still confused, however, and according to #156, the impression that remains is that this request will solve the problems altogether?

Still in dev version, however... This fluctuation of circumstances is very tricky.

**Comment by raratiru** [comment]
Saving the changed files of this commit in ```static/leaflet/draw/```, I receive the following error:

```TypeError: L.drawLocal.draw.toolbar.finish is undefined
http://127.0.0.1:8000/static/leaflet/draw/leaflet.draw.js
(Line 9, col 14265)```

**Comment by leplatrem** [comment]
Thanks @raratiru for the feedback! 

I close the PR, please feel free to re-open with a stable tag of leaflet.draw that works !

**Comment by raratiru** [comment]
That's cool, I am glad I helped to delineate the situation.

However, it seems that I will not avoid a manual install of leaflet in my effort to work with it on a tablet.

**Comment by RaphaelGeode** [comment]
A simple fix for the error show before : 
```javascript
<script type="text/javascript">
    L.drawLocal.draw.toolbar.finish = {title:'Finish drawing', text:'Finish'};
</script>
```

**Comment by raratiru** [comment]
@RaphaelGeode Thank you for sharing, this is very useful under the current circumstances.

**Comment by leplatrem** [comment]
Thanks for helping out!

Do not hesitate open a PR upgrading to Leaflet 1.0 and/or leaflet-draw 0.3.2, it'll be merged if feedback is positive!

**Pull request closed without merging**
